[project]
name = "ustomer-service"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aiomysql>=0.3.2", # 异步MySQL驱动
    "cryptography>=46.0.7", # 加密库
    "fastapi>=0.136.0", # FastAPI框架
    "httpx>=0.28.1", # HTTP客户端
    "jinja2>=3.1.6", # 模板引擎
    "langchain>=1.2.15", # 对话引擎
    "langchain-openai>=1.1.14", # 对话引擎的OpenAI实现
    "pydantic-settings>=2.13.1", # 配置管理
    "pyyaml>=6.0.3", # YAML解析
    "sqlalchemy>=2.0.49", # 数据库ORM
    "uvicorn>=0.44.0", # ASGI服务器
]
